package chapter11;

public class ExceptionEx3 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		try {
			int[] arr = {1,2,3};
			System.out.println(arr[3]);
			System.out.println(3/0);
			Integer.parseInt("a");					
		} catch (ArithmeticException e) {
			System.out.println("0으로 나눌 수 없음");
		}
		
		
		System.out.println(1);
		System.out.println(2);
		System.out.println(3/0);
		System.out.println(4);
		System.out.println(5);
		System.out.println(6);
	}

}
